# Generated by Django 4.2.6 on 2023-10-29 17:57

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('imagem', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
            ],
            bases=(models.Model, phonenumber_field.modelfields.PhoneNumberField),
        ),
    ]
